apiVersion: v1
kind: ConfigMap
metadata:
  name: matching-config
data:
  REDIS_ADDR: "matching-redis:6379"
  KAFKA_ADDR: "matching-kafka:9092"
  HTTP_PORT: "8091"
  GRPC_PORT: "9095"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://matching-postgres:5432/matching"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "matching-kafka:9092"
  MATCHING_ENGINE_HOST: "matching-engine"
  MATCHING_ENGINE_GRPC_PORT: "9095"
