apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  DATABASE_URL: "postgres://ecommerce:ecommerce@postgres:5432/ecommerce?sslmode=disable"
  REDIS_ADDR: "redis:6379"
  KAFKA_BROKERS: "kafka:9092"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/ecommerce"
  SPRING_DATASOURCE_USERNAME: "ecommerce"
  INVENTORY_GRPC_HOST: "inventory-service"
  INVENTORY_GRPC_PORT: "9090"
