apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-collector-config
  namespace: observability
data:
  KAFKA_BROKERS: kafka.observability.svc.cluster.local:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: observability
  labels:
    app: metrics-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
        - name: metrics-collector
          image: localhost:5001/metrics-collector:281b9a4
          ports:
            - containerPort: 28081
              name: http
            - containerPort: 28090
              name: grpc
          envFrom:
            - configMapRef:
                name: metrics-collector-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 28081
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 28081
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
  namespace: observability
spec:
  selector:
    app: metrics-collector
  ports:
    - name: http
      port: 28081
    - name: grpc
      port: 28090
