// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsCollectorService_IngestMetric_FullMethodName = "/metrics.MetricsCollectorService/IngestMetric"
)

// MetricsCollectorServiceClient is the client API for MetricsCollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsCollectorServiceClient interface {
	IngestMetric(ctx context.Context, in *IngestMetricRequest, opts ...grpc.CallOption) (*IngestMetricResponse, error)
}

type metricsCollectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsCollectorServiceClient(cc grpc.ClientConnInterface) MetricsCollectorServiceClient {
	return &metricsCollectorServiceClient{cc}
}

func (c *metricsCollectorServiceClient) IngestMetric(ctx context.Context, in *IngestMetricRequest, opts ...grpc.CallOption) (*IngestMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestMetricResponse)
	err := c.cc.Invoke(ctx, MetricsCollectorService_IngestMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsCollectorServiceServer is the server API for MetricsCollectorService service.
// All implementations must embed UnimplementedMetricsCollectorServiceServer
// for forward compatibility.
type MetricsCollectorServiceServer interface {
	IngestMetric(context.Context, *IngestMetricRequest) (*IngestMetricResponse, error)
	mustEmbedUnimplementedMetricsCollectorServiceServer()
}

// UnimplementedMetricsCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsCollectorServiceServer struct{}

func (UnimplementedMetricsCollectorServiceServer) IngestMetric(context.Context, *IngestMetricRequest) (*IngestMetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestMetric not implemented")
}
func (UnimplementedMetricsCollectorServiceServer) mustEmbedUnimplementedMetricsCollectorServiceServer() {
}
func (UnimplementedMetricsCollectorServiceServer) testEmbeddedByValue() {}

// UnsafeMetricsCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsCollectorServiceServer will
// result in compilation errors.
type UnsafeMetricsCollectorServiceServer interface {
	mustEmbedUnimplementedMetricsCollectorServiceServer()
}

func RegisterMetricsCollectorServiceServer(s grpc.ServiceRegistrar, srv MetricsCollectorServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricsCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsCollectorService_ServiceDesc, srv)
}

func _MetricsCollectorService_IngestMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsCollectorServiceServer).IngestMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsCollectorService_IngestMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsCollectorServiceServer).IngestMetric(ctx, req.(*IngestMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsCollectorService_ServiceDesc is the grpc.ServiceDesc for MetricsCollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsCollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.MetricsCollectorService",
	HandlerType: (*MetricsCollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestMetric",
			Handler:    _MetricsCollectorService_IngestMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}
